### ISSUE TITLE
OpenSSL copyright?

### ISSUE THREAD

**Issue by levitte** [open-quantum-safe/oqs-provider#4]
There are a number of files in [oqsprov/](https://github.com/open-quantum-safe/oqs-provider/tree/main/oqsprov) that have the OpenSSL copyright boilerplate, which gives copyright to the OpenSSL Authors, which I understand is historical, since this was previously a patchset for OpenSSL proper.

I don't think that's something you want at this point, and I can't see anything wrong with simply removing that boilerplate.  What you still have in there that could remind anyone of the built-in OpenSSL providers, it's mostly bread-and-butter lines that are only vaguely similar.

**Comment by baentsch** [comment]
ACK. We'd probably take the (lib)OQS marking route. Looking at that again, though, `// SPDX-License-Identifier: Apache-2.0 AND MIT` is a "bit terse".... @dstebila Suggestions?

**Comment by dstebila** [comment]
In liboqs for files we created, we did not put individual license information in each file beyond the SPDX-License-Identifier header, but there was a LICENSE.txt at the root which contained that information.  I think that would be okay here.

**Comment by baentsch** [comment]
Resolved with https://github.com/open-quantum-safe/oqs-provider/commit/d6223cb1984caeaba02cf8ff89108dad2cb37046

**Comment by levitte** [comment]
You missed a spot :wink:

https://github.com/open-quantum-safe/oqs-provider/blob/d6223cb1984caeaba02cf8ff89108dad2cb37046/test/oqs_test_groups.c#L17-L24

**Comment by baentsch** [comment]
> You missed a spot 

Thanks for the catch. And it was more than one. Lesson: No change too small to not botch it :-( Hopefully #5 gets this right. I won't bother you to review it (but won't stop you :-)

**Comment by levitte** [comment]
[ahem] I might look over your virtual shoulder a little now and then.  Just the fact that others are *already* playing with external provider is *exciting*
